# Generated by Django 4.0.4 on 2022-05-04 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='login',
            new_name='log',
        ),
    ]
