# Generated by Django 4.0.4 on 2022-05-04 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_rename_login_log'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='log',
            new_name='Login',
        ),
    ]
