# Generated by Django 4.0.4 on 2022-05-09 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Login',
        ),
        migrations.AlterField(
            model_name='contact',
            name='comment',
            field=models.TextField(max_length=122),
        ),
    ]
