# Generated by Django 4.0.4 on 2022-05-09 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_delete_login_alter_contact_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
